### ISSUE TITLE
File paths in output need `http://` prefix to match URL_REGEXP in karma/lib/reporter.js

### ISSUE THREAD

**Issue by brianmhunt** [nikku/karma-browserify#137] opened 2015-07-15 23:41 UTC
The files output by karma-browserify seem to not match the [general reporter regular expression](https://github.com/karma-runner/karma/blob/master/lib/reporter.js#L24) for formatting errors, and so source maps are not exposed.

I am not sure if it is easier for karma-browserify to add the `http://` to the beginning of the path in the error messages, or for karma-runner/karma to update the regular expression – so I am cross-posting this issue with karma-runner/karma#1495

**Comment by brianmhunt** [comment] 2015-07-16 00:04
If I may add, as it may be related: the source map files and lines produced via `coffeeify` are not to the coffeescript but to the compiled javascript. Looking into that further to see if it is related. Cheers.

**Comment by nikku** [comment] 2015-07-16 21:23
We receive a number of errors with source maps lately. It seems as if karma + karma-browserify + browserify can sometimes exchange the source map and sometimes not.

**Comment by brianmhunt** [comment] 2015-07-16 23:42
@nikku Thanks.

Just for the sake of completeness, I tried all the seemingly reasonable permutations of `commondir` and `fullPaths`, but they changed nothing.

By the time they get to [`createErrorFormatter:39`](https://github.com/karma-runner/karma/blob/master/lib/reporter.js#L39) in `karma/lib/reporter.js` they errors spit out are all something like:

> AssertionError: expected 'x' to equal 'y'
    at Context.<anonymous> (absolute/var/folders/vl/_5jh_5_n3njb7rfcg5tr87p80000gn/T/7b875eecd57ed38e48b76b5fd3aa873f.browserify?07c629ce4f57a079e0139149a80eecf99972dca6:29293:19)

whereas the url should (according to the `URL_REGEXP`) be something like:

> **http://localhost:9876/**absolute/var/folders/vl/_5jh_5_n3njb7rfcg5tr87p80000gn/T/7b875eecd57ed38e48b76b5fd3aa873f.browserify?07c629ce4f57a079e0139149a80eecf99972dca6:29293:19

**Comment by nikku** [comment] 2015-07-20 12:26
I actually think this is a browser issue.

Running against PhantomJS stack traces would properly be prefixed with `http://localhost:9876/absolute/...`. Running a test suite against Chrome would result in stack trace entries like `absolute/...`.

See if you can reproduce this issue.

**Comment by brianmhunt** [comment] 2015-07-23 12:32
Thanks @nikku – I cannot speak for PhantomJS or Safari or IE with these tests, offhand, but the problem appears to exhibit in Firefox as well i.e. the error pinpoints are reported as something like

> `/var/folders/8v/ntgprb8d3bq58y8ffw4k01kc0000gn/T/470335fca4dc3aa7ab541b4d0d1c680e.browserify:17298:5`

i.e. lacking `http://.../`

Will see if I can put together a minimal test case.

**Comment by brianmhunt** [comment] 2015-07-23 12:59
Here's a minimum working example that should run in multiple platforms https://gist.github.com/brianmhunt/e9b54d35af5c6537e3c8

**Comment by nikku** [comment] 2015-07-23 14:00
All right. I presume we should wait for some time to let these browsers (or karma) come up with respective fixes. The only thing we do is [parsing the source map an providing it to karma](https://github.com/nikku/karma-browserify/blob/master/lib/bro.js#L37).

**Comment by brianmhunt** [comment] 2015-07-23 14:11
Ok, thanks @nikku – the issue is not here by the looks of it. I'll note the MWE on the Karma issue.

**Comment by nikku** [comment] 2015-08-17 10:41
Seems to be fixed in karma@0.13

**Closed by nikku** 2015-08-17 10:41 UTC

**Comment by brianmhunt** [comment] 2015-08-17 13:43
Thanks @nikku- yes you are right- we fixed up the regex in karma reporter, sorry for not updating this issue.
