### ISSUE TITLE
"No provider for "framework:browserify"!

### ISSUE THREAD

**Issue by cbelden** [nikku/karma-browserify#133] opened 2015-06-23 16:51 UTC
When running `karma start` I get the following error:
```
Error: No provider for "framework:browserify"! (Resolving: framework:browserify)

    at error (C:\Users\cbelden\AppData\Roaming\npm\node_modules\karma\node_modules\di\lib\injector.js:22:68)
    at Object.parent.get (C:\Users\cbelden\AppData\Roaming\npm\node_modules\karma\node_modules\di\lib\injector.js:9:13)
    at get (C:\Users\cbelden\AppData\Roaming\npm\node_modules\karma\node_modules\di\lib\injector.js:54:19)
    at C:\Users\cbelden\AppData\Roaming\npm\node_modules\karma\lib\server.js:31:14
    at Array.forEach (native)
    at start (C:\Users\cbelden\AppData\Roaming\npm\node_modules\karma\lib\server.js:30:21)
    at invoke (C:\Users\cbelden\AppData\Roaming\npm\node_modules\karma\node_modules\di\lib\injector.js:75:15)
    at Object.exports.start (C:\Users\cbelden\AppData\Roaming\npm\node_modules\karma\lib\server.js:312:12)
    at Object.exports.run (C:\Users\cbelden\AppData\Roaming\npm\node_modules\karma\lib\cli.js:229:25)
    at Object.<anonymous> (C:\Users\cbelden\AppData\Roaming\npm\node_modules\karma\bin\karma:3:23)
```

#### System Information:
Windows 8.1
iojs 32bit v2.3.0
karma v0.12.36
karma-browserify v4.2.1

#### karma.conf.js
``` javascript
module.exports = function(config) {
  config.set({

    // base path that will be used to resolve all patterns (eg. files, exclude)
    basePath: '',


    // frameworks to use
    // available frameworks: https://npmjs.org/browse/keyword/karma-adapter
    frameworks: ['browserify', 'mocha', 'chai'],

    // list of files / patterns to load in the browser
    files: [
        './app/**/*.test.js',
    ],

    // list of files to exclude
    exclude: [
    ],


    // preprocess matching files before serving them to the browser
    // available preprocessors: https://npmjs.org/browse/keyword/karma-preprocessor
    preprocessors: {
        './app/**/*.test.js': 'browserify'
    },

    browserify: {
        debug: true
    },
    // ...
}
```

#### package.json
``` javascript
{
  //...
  "devDependencies": {
    "karma-browserify": "^4.2.1",
    "karma-chai": "^0.1.0",
    "karma-mocha": "^0.2.0",
    "karma-nyan-reporter": "0.0.60",
    "rimraf": "^2.4.0"
  }
  //...
}
```

I've confirmed that all dev dependencies are installed in the node_modules folder. I've tried clearing the npm cache and re-installing all dependencies. While debugging, I noticed that the mocha and chai frameworks were correctly registered, just browserify is missing.

Thanks!

**Comment by cbelden** [comment] 2015-06-23 16:57
After installing all dependencies globally, karma ran correctly. Is the expectation that the user will have karma-browserify installed globally? Thanks

**Comment by bendrucker** [comment] 2015-06-23 17:08
No

**Comment by nikku** [comment] 2015-07-16 21:22
Closing this. Feel free to post additional hints / questions for a reopen.

**Closed by nikku** 2015-07-16 21:22 UTC

**Comment by rehia** [comment] 2015-07-20 22:21
I couldn't even run the provided examples 
Finally fixed by installing `karma-browserify` globally.

**Comment by nikku** [comment] 2015-07-21 13:47
Did not test karma-browserify against v0.13.2. Feel free to run the test suite against it and tell me about your findings.

**Comment by MarkLeMerise** [comment] 2015-07-21 20:59
I have been having the exact same issue with `karma@0.13.2` and `karma-browserify@4.2.1` and also had the issue solved with `npm install -g karma-browserify`.

FWIW, I think this issue is `karma`-related as I had the exact same issue (and resolution) with the `karma-phantomjs-shim` package.

**Comment by rehia** [comment] 2015-07-21 21:47
@MarkLeMerise Weird, because I had the same failed tests as the ones you ran with karma 0.12.9, but with karma 0.13.2 o_O

**Comment by nikku** [comment] 2015-07-22 07:51
@MarkLeMerise What platform are you running on?

**Comment by MarkLeMerise** [comment] 2015-07-22 14:14
@nikku Mac OS X Yosemite 10.10.4 with node 0.12.7

**Comment by nikku** [comment] 2015-07-26 09:16
Can reproduce that I get five test failures using the latest dependencies. I'll look into it.
