### ISSUE TITLE
Sourcemaps (debug:true) do not seems to works with reactify transform

### ISSUE THREAD

**Issue by clementdubois** [nikku/karma-browserify#122] opened 2015-04-17 08:44 UTC
I'm running karma-browserify (with mocha and chai as frameworks) and I use reactify and babelify as transforms.

When a test fail I don't have the sourcemaps support (I use debug:true in browserify).

Here is my karma.conf.js : 
```javascript
module.exports = function(config) {
  config.set({
    basePath : "",
    browserNoActivityTimeout: 60000,
    frameworks : ["browserify", "mocha", "chai"],
    files : [
      "karma.bind.js",
      "../src/**/*.spec.js",
    ],
    preprocessors : {
      "../src/**/*.spec.js" : ["browserify"],
    },
    browserify : {
      debug : true,
      transform : [["reactify"], ["babelify"]],
      extensions : [".js", ".jsx"],
    },
    reporters : ["progress"],
    port : 9876,
    colors : true,
    logLevel : config.LOG_INFO,
    autoWatch : false,
    browsers : ["PhantomJS"],
    singleRun : true,
  });
};
```

And when a test fail here is a typical log : 
```
 1) AssertionError: expected { Object (getDOMNode, props, ...) } to not exist
                      at http://localhost:9876/absolute/var/folders/mx/6fy7wf4j1msgpblw8s09fq2m0000gn/T/914a62d6608f3ef65ef1cb0e680c0575.browserify:9919
                      at http://localhost:9876/absolute/var/folders/mx/6fy7wf4j1msgpblw8s09fq2m0000gn/T/914a62d6608f3ef65ef1cb0e680c0575.browserify:10336
                      at http://localhost:9876/absolute/var/folders/mx/6fy7wf4j1msgpblw8s09fq2m0000gn/T/914a62d6608f3ef65ef1cb0e680c0575.browserify:13098

```

Did I do something wrong or is there some kind of conflict between the debug mode of browserify and the transforms applied for React with ES6 ?

**Comment by bendrucker** [comment] 2015-04-17 13:04
Doesn't babel ship with react support out of the box? It looks like reactify tries to support source maps but I'm inclined to assign the blame there. I use bableify + karma-browserify and have no issues w/ source maps.

**Comment by clementdubois** [comment] 2015-04-17 14:17
You're right I just use babelify now but the logs are still the same : 
```
at http://localhost:9876/absolute/var/folders/mx/6fy7wf4j1msgpblw8s09fq2m0000gn/T/914a62d6608f3ef65ef1cb0e680c0575.browserify:9919
```

**Comment by brianmhunt** [comment] 2015-05-04 18:52
This is probably the same issue, so I'll just add it as a comment: Source maps used to work with Coffeeify, but in the last couple weeks it just stopped – presumably because I updated to a version that no longer works with source maps. Will post more if I figure out what happened.

**Comment by nikku** [comment] 2015-05-21 07:32
Looks as if there is an issue with source map loading. Maybe 59e0c2de2820151823c36696734c3d7a25de7586 resolves it.

**Comment by nikku** [comment] 2015-05-21 07:42
Please check if the issue is fixed in [v4.2.1](https://github.com/nikku/karma-browserify/releases/tag/v4.2.1).

**Closed by nikku** 2015-05-21 07:42 UTC

**Comment by ponelat** [comment] 2015-07-15 12:24
Any confirmation this works? I've run into myself (just updated to v4.2.1 after seeing this comment) and I don't get source maps.... karma-browserify@4.2.1 + babelify@6.0.2 + karma-source-map-support@1.0.0

If no-one has a working setup, I can try and create a minimal example. I would like to know if it's a configuration error on my part.

**Comment by brianmhunt** [comment] 2015-07-15 14:06
@ponelat I've mucked with it quite a bit just recently, to no avail, so I believe it's worthwhile to create a minimal working example.

**Comment by ponelat** [comment] 2015-07-15 15:45
Ok, I'll hack it out tomorrow if I get a chance... no sourcemaps means my error tracking goes something like.... "I wonder if it was that line..."
