### ISSUE TITLE
Windows is awful

### ISSUE THREAD

**Issue by smrq** [nikku/karma-browserify#78] opened 2015-01-06 21:42 UTC
As of 2.x: Something somewhere in the bundling stack is changing `/`s to `\\`s on Windows, causing `Cannot find module 'C:/some/absolute/path.js'` type errors.  Basically, the generated bundle exposes ids of the form `C:\\some\\absolute\\path.js`, but the stubs use `require('C:/some/absolute/path.js')`.

Best fix: convince Microsoft to use `/`s like normal people.  Alternatively, either do a `path.resolve` on the paths in the stubs to normalize the slash direction to the current OS standard, or figure out what is changing the slash direction and make it stop doing it.

(I'm working on the latter, but not getting much of anywhere yet.)

Some tests fail on Windows as well; my guess is this is probably related, although the errors are not all particularly verbose so it's hard to tell.

**Comment by smrq** [comment] 2015-01-06 22:07
Oh, it would help if I would actually look at what code is running.

The problem is introduced by the fork of Browserify.  Looks like it's from this commit: https://github.com/Nikku/node-browserify/commit/5fc4ef50e2cbd8f566930a7a357c4d388de9767e

The call to `path.resolve(basedir, file)` would do exactly this.  Changing that line to: `path.resolve(basedir, file).replace(/\\/g, '/')` fixes the issue, as well as some of the tests.

**Comment by Nikku** [comment] 2015-01-07 07:31
I will have a look into the fix and the failing test case. I remember to have a Windows machine lying around somewhere.

**Comment by Jmaharman** [comment] 2015-01-10 12:18
I've just made this change locally and it's fixed my issue.

**Comment by divmgl** [comment] 2015-01-13 00:56
Wow, this was my issue. Unbelievable. Using Windows at work and this thing has been bugging me for quite a while now. It's incredibly annoying that these workarounds are needed for Windows.

**Comment by Nikku** [comment] 2015-01-13 07:17
I will look into it as soon as I get hold on a Windows device!

**Comment by divmgl** [comment] 2015-01-16 07:32
I was able to resolve this for some paths, but trying to traverse up a directory tree causes problems.

**Comment by rahulbpatel** [comment] 2015-01-16 23:22
So what's the workaround for version 2.0.0 on Windows or should we just use v1.0.1?

**Comment by bendrucker** [comment] 2015-01-17 00:03
Stay tuned. Browserify just landed some changes that may resolve the need to have a fork. 

https://github.com/substack/node-browserify/compare/19061183e17e462e7bf803e98f0d2b5220ff57e1...8.1.1

**Comment by nikku** [comment] 2015-01-17 12:49
Nope, we still need the fork. Do not actually know what 8.1.1 fixed.

**Closed** 2015-01-18 16:49 UTC
Labels: bug, platform:Win

**Comment by nikku** [comment] 2015-01-18 16:51
Could you guys check that the latest master resolves the issue for you?

I am happy to release a major version bump if things work fine for you on Windows.

**Comment by smrq** [comment] 2015-01-18 19:46
Thanks for the effort @nikku, I'll check tomorrow when I get back to my work machine.

**Comment by rahulbpatel** [comment] 2015-01-18 20:49
Works for me, thanks!

**Comment by smrq** [comment] 2015-01-19 20:02
The update fixes things for me as well.  Thanks!

**Comment by divmgl** [comment] 2015-01-23 02:18
This issue is occurring again in 3.0.0 just published to NPM two hours ago.

**Comment by divmgl** [comment] 2015-01-23 02:22
This issue is still occurring on Windows 8.1 with latest release 3.0.0.

**Comment by nikku** [comment] 2015-01-23 07:46
@divmgl Please open a new issue and attach an example project that reproduces the problems for you.

**Comment by divmgl** [comment] 2015-01-25 01:30
Opened #89

**Comment by divmgl** [comment] 2015-02-04 23:08
#89 This issue has been confirmed as resolved on Windows 8
