### ISSUE TITLE
'require is not defined'

### ISSUE THREAD

**Issue by alexreardon** [nikku/karma-browserify#139] opened 2015-07-29 04:30 UTC
I am getting the error `Uncaught ReferenceError: require is not defined` when attempting to use `karma-browserify` on line 1; even though there is no require statement on line 1. Has anyone seen this before?

```
// Karma configuration

module.exports = function (karma) {
    karma.set({

        // base path that will be used to resolve all patterns (eg. files, exclude)
        basePath: '',
        frameworks: ['expect', 'mocha', 'sinon', 'browserify'],
        files: [
            'components/**/*.test.js'
        ],
        exclude: [],
        preprocessors: {
            'components/**/*.test.js': ['browserify']
        },
        reporters: ['progress'],
        port: 9876,
        colors: true,
        logLevel: karma.LOG_INFO,
        autoWatch: false,
        browsers: ['Chrome'],
        singleRun: true
    });
};
```

**Comment by alexreardon** [comment] 2015-07-30 21:40
This is occurring even when there is no `require` in the included file

**Comment by azer** [comment] 2015-07-31 00:44
I'm also getting same error with example configuration.

**Comment by nikku** [comment] 2015-07-31 06:50
The latest browserify/watchify release introduced breaking changes with a number of incompatibilities. Try to use `watchify <= 3.1.x && browserify <= 10.2.1` in your project and see if it fixes the issue.

Karma `>= 0.13.x` may have introduced some breaking changes, too. See #138.

**Comment by alexreardon** [comment] 2015-08-02 22:54
Can you recommend a safe version of `karma-browserify` to peg to?

**Comment by nikku** [comment] 2015-08-03 17:37
Working on it. Need to patch karma-browserify with a save version. For the moment, include a fixed version of watchify and browserify (see above) with your project. Together with npm depencency resolving this should add the respective libraries to the search path.

**Comment by alexreardon** [comment] 2015-08-04 07:49
Thanks @nikku

**Comment by nikku** [comment] 2015-08-04 17:25
See if the latest version `v4.2.2` fixes the issue for you.

**Comment by alexreardon** [comment] 2015-08-04 22:13
I installed the following:
```
"karma-browserify": "nikku/karma-browserify#7c67ac26c3b08476017fd82275b30ace3ff3957a",
```
(I would have installed 4.2.2 but it looks like it is not published on npm yet)

However, it looks as though I am getting the same issue.

**Comment by alexreardon** [comment] 2015-08-11 22:18
Sadly I can confirm this is still occurring in `4.3.0`. I am currently investigating

**Comment by nikku** [comment] 2015-08-12 06:15
Could you put up an example project somewhere that reproduces the issue? I cannot reproduce the issue in my project setups.

**Comment by ebednarz** [comment] 2015-08-21 07:56
@nikku FWIW, I had the same issue yesterday and downgrading to the latest karma 12.* fixed it for me. I'll see if I can put together a minimal test case today or tomorrow.

**Comment by nikku** [comment] 2015-09-01 14:51
Closing this for now due to inactivity. I am going to reopen this issue, if anyone can provide me with a test case that reproduces the behavior.

**Closed by nikku** 2015-09-01 14:51 UTC
